#!/bin/bash

show_help() {
cat << EOF
Usage: ${0##*/} [<command>] [<args>]
A simple CLI for managing hawkbit

    -h, --help  display this help and exit

Subcommands, for more information for any subcommand use:
hawkbitctl <command> --help

    tags        Manage target tags
    targets     Manage targets
EOF
}

if [[ "$1" =~ -h|--help ]]; then
    show_help
    exit 0
elif [[ "$1" == "tags" ]]; then
    shift
    ./tags.sh "$@"
elif [[ "$1" == "targets" ]]; then
    shift
    ./targets.sh "$@"
elif [[ -n "$2" ]]; then
    echo >&2 "Unknown command $2"
    show_help
    exit 1
else
    show_help
    exit 0
fi
