#!/bin/bash

show_help() {
cat << EOF
Usage: ${0##*/} [<command>] [<args>]
A simple CLI for managing hawkbit

    -h, --help  display this help and exit

Subcommands, for more information for any subcommand use:
hawkbitctl <command> --help

    tags                Manage target tags
    targets             Manage targets
    rollouts            Manage rollouts
    softwaremodules     Manage software modules
    distributionsets    Manage distribution sets
EOF
}

DIR="${HAWKBITCTL_SOURCEDIR:-/usr/lib/hawkbitctl}"

if [[ "$1" =~ -h|--help ]]; then
    show_help
    exit 0
elif [[ "$1" == "tags" ]]; then
    shift
    "$DIR/tags.sh" "$@"
elif [[ "$1" == "targets" ]]; then
    shift
    "$DIR/targets.sh" "$@"
elif [[ "$1" == "rollouts" ]]; then
    shift
    "$DIR/rollouts.sh" "$@"
elif [[ "$1" == "softwaremodules" ]]; then
    shift
    "$DIR/softwaremodules.sh" "$@"
elif [[ "$1" == "distributionsets" ]]; then
    shift
    "$DIR/distributionsets.sh" "$@"
elif [[ -n "$2" ]]; then
    echo >&2 "Unknown command $2"
    show_help
    exit 1
else
    show_help
    exit 0
fi
