#!/bin/bash

DIR="${HAWKBITCTL_SOURCEDIR:-/usr/lib/hawkbitctl}"

# shellcheck disable=SC1091
# shellcheck source=src/config.sh
. "$DIR/config.sh"

set -u

data=$(cat /dev/stdin)

curl -s "${CURL_AUTH_ARGS[@]}" \
    "$API_URL""$1" \
    -X POST \
    -H 'Content-Type: application/json;charset=UTF-8' \
    --output "$2" \
    --write-out "%{http_code}" \
    -d "$data"
