#!/bin/bash

# shellcheck disable=SC1091
. config.sh

set -u

data=$(cat /dev/stdin)

curl -s "${CURL_AUTH_ARGS[@]}" \
    "$API_URL""$1" \
    -X POST \
    -H 'Content-Type: application/json;charset=UTF-8' \
    -d "$data"
